import type { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { ParsedUrlQuery } from 'querystring'
import assert from 'assert'
import { loadRule, loadRules, Rule } from '../../lib/rules'

interface Props {
  rule: Rule
}

const RulePage: NextPage<Props> = ({
  rule
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`${rule.name} - Among Us Rulebook`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="referrer" content="no-referrer" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {rule.name}
        </h1>
        <p>
          推奨人数: {rule.recommendedParticipants}
        </p>
        <h2>バージョン</h2>
        <ul>
          <li>
            Among Us:{' '}
            <a href={`https://among-us.fandom.com/wiki/Among_Us/Version_history#${rule.versions.amongUs}`}>
              {rule.versions.amongUs}
            </a>
          </li>
          {rule.versions.extremeRoles ? (
            <li>
              Extreme Roles:{' '}
              <a href={`https://github.com/yukieiji/ExtremeRoles/releases/tag/v${rule.versions.extremeRoles}`}>
                {rule.versions.extremeRoles}
              </a>
            </li>
          ) : ''}
          {rule.versions.submerged ? (
            <li>
              Submerged: {rule.versions.submerged}
            </li>
          ) : ''}
        </ul>
        <p>
          {rule.imageUrls.map((imageUrl, index) => (
            <img src={imageUrl} width="640px" height="360px" key={index} alt={`${index}`} />
          ))}
        </p>
      </main>
    </div>
  )
}

interface UrlQuery extends ParsedUrlQuery {
  ruleId: string
}

export const getStaticPaths: GetStaticPaths<UrlQuery> = async () => {
  const rules = loadRules()

  const paths = rules.map((rule) => {
    return {
      params: {
        ruleId: rule.id
      }
    }
  })

  return {
    paths,
    fallback: false
  }
}

export const getStaticProps: GetStaticProps<Props, UrlQuery> = async (context) => {
  assert(context.params !== undefined)
  const { ruleId } = context.params

  const rule = loadRule(ruleId)

  return {
    props: {
      rule
    }
  }
}

export default RulePage
