import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { loadRules, Rule } from '../lib/rules'
import Link from 'next/link'

interface Props {
  rules: Rule[]
}

const RulesPage: NextPage<Props> = ({
  rules
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Among Us Rulebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="referrer" content="no-referrer" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Among Us Rulebook
        </h1>
        <h2>
          Rules
        </h2>
        <ul>
        {rules.map((rule) => (
          <li key={rule.id}>
            <Link href={`/rules/${rule.id}/`}>
              {rule.name}
            </Link>
          </li>
        ))}
        </ul>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps<Props> = async (context) => {
  const rules = loadRules()

  return {
    props: {
      rules
    }
  }
}

export default RulesPage
